/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_MPU6050_PB_H_INCLUDED
#define PB_MPU6050_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MPU6050_Message {
    float acceleration_x;
    float acceleration_y;
    float acceleration_z;
    float rotation_x;
    float rotation_y;
    float rotation_z;
} MPU6050_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MPU6050_Message_init_default             {0, 0, 0, 0, 0, 0}
#define MPU6050_Message_init_zero                {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MPU6050_Message_acceleration_x_tag       1
#define MPU6050_Message_acceleration_y_tag       2
#define MPU6050_Message_acceleration_z_tag       3
#define MPU6050_Message_rotation_x_tag           4
#define MPU6050_Message_rotation_y_tag           5
#define MPU6050_Message_rotation_z_tag           6

/* Struct field encoding specification for nanopb */
#define MPU6050_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    acceleration_x,    1) \
X(a, STATIC,   SINGULAR, FLOAT,    acceleration_y,    2) \
X(a, STATIC,   SINGULAR, FLOAT,    acceleration_z,    3) \
X(a, STATIC,   SINGULAR, FLOAT,    rotation_x,        4) \
X(a, STATIC,   SINGULAR, FLOAT,    rotation_y,        5) \
X(a, STATIC,   SINGULAR, FLOAT,    rotation_z,        6)
#define MPU6050_Message_CALLBACK NULL
#define MPU6050_Message_DEFAULT NULL

extern const pb_msgdesc_t MPU6050_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MPU6050_Message_fields &MPU6050_Message_msg

/* Maximum encoded size of messages (where known) */
#define MPU6050_Message_size                     30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
