name: VCU CI

on:
  push:

jobs:
  Lint-Build-Check-VCU:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4

      # Update PlatformIO
      - name: Setup PlatformIO
        run: pip install --upgrade platformio

      # Format Check
      - name: Format Check
        uses: DoozyX/clang-format-lint-action@v0.16
        if: always()
        with:
          source: .

      # Build with PlatformIO
      - name: Compile VCU Code
        if: always()
        run: |
          pio run